Remove enum typedef
As far as I can tell, the ELEMENT_TYPE symbol isn't being used by this
library. It conflicts with a symbol defined in the Windows SDK:

libaudiofile\alac\ALACBitUtilities.h(68): error C2371: 'ELEMENT_TYPE':
redefinition; different basic types (compiling source file
audiofile\libaudiofile\alac\ALACDecoder.cpp)
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winioctl.h(3944):
note: see declaration of 'ELEMENT_TYPE' (compiling source file
libaudiofile\alac\ALACDecoder.cpp)